name: Testes Automáticos - Grupo 4

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Iniciar a API em segundo plano
      run: |
        uvicorn api:app --host 127.0.0.1 --port 8000 &
        sleep 3

    - name: Executar testes de unidade
      run: pytest test_api.py

    - name: Executar testes de integração
      run: pytest test_integracao.py
